name: Generate UML Diagrams

on:
  push:
    paths:
      - 'esp32/include/**'

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: pip install -r requirements.txt  # Installer les dépendances
    - name: Run PlantUML Builder
      run: python docs/plantUmlBuilder.py  # Exécuter le script Python
    - name: Install PlantUML
      run: sudo apt-get install plantuml
    - name: Generate UML Diagrams
      run: plantuml docs/esp32.puml -tsvg  # Générer l'image .svg
    - name: Commit UML Diagram
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add docs/esp32.svg
        git commit -m "Updated UML diagram"
    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}
